---
site_name: terraform-azurerm-postgresql-server

repo_name: padok-team/terraform-azurerm-postgresql-server
repo_url: https://github.com/padok-team/terraform-azurerm-postgresql-server

plugins:
  - techdocs-core
